{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"tuid":"${fld:tuid}"
		,"item_name_cn":"${fld:item_name_cn@js}"
		,"item_name_en":"${fld:item_name_en@js}"
		,"col_num":"${fld:col_num}"
		,"show_order":"${fld:show_order}"
		,"remark":"${fld:remark@js}"
		,"item_code":"${fld:item_code@js}"
		,"linkage_document_alias":"${fld:linkage_document_alias@js}"
	},
	</rows>
	{}
]}