{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{		
			"application_id":"${fld:application_id@js}",
		    "vc_code":"${fld:code@js}",
		    "vc_name":"${fld:classroom_name@js}",
		    "f_area":"${fld:area}",
		    "vc_type":"${fld:room_type@js}",
		    "i_limit":"${fld:limit_num}",
		    "vc_remark":"${fld:remark@js}",
		    "i_status":"${fld:status@js}",
		    "vc_ispreparedevice":"${fld:ispreparedevice@js}"
	},
	</rows>
	{}
]}
