{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"application_id":"${fld:application_id@js}",
		"show_order":"${fld:_rowNumber}",
		"vc_contractcode":"${fld:vc_contractcode@js}",
		"vc_name":"${fld:vc_name@js}",
		"i_sex":"${fld:i_sex@js}",
		"vc_mobile":"${fld:vc_mobile@js}",
		"f_normalmoney":"${fld:f_normalmoney}",
		"i_stage_times":"${fld:i_stage_times}",
		"i_stage_times_pay":"${fld:i_stage_times_pay}",
		"amount_owe":"${fld:amount_owe}",
		"should_resver":"${fld:should_resver}",
		"vc_iuser":"${fld:vc_iuser@js}",
		"c_idate":"${fld:c_idate}"
	},
	</rows>
	{}
]}