document.formEditor.vc_code.value = "${fld:code@js}";
document.formEditor.i_status.value = "${fld:status}";
document.formEditor.vc_name.value = "${fld:name@js}";
document.formEditor.i_sex.value = "${fld:sex}";
document.formEditor.vc_club.value = "${fld:org_id}";
ccms.util.setCheckboxValue('vc_club',"${fld:fullname@js}","formEditor");
document.formEditor.c_birthdate.value = "${fld:birthdate}";
document.formEditor.vc_rank.value = "${fld:rank@js}";
document.formEditor.vc_email.value = "${fld:email@js}";
document.formEditor.vc_idnumber.value = "${fld:idnumber@js}";
document.formEditor.vc_nation.value = "${fld:nation@js}";
document.formEditor.vc_hometel.value = "${fld:hometel@js}";
document.formEditor.vc_addr.value = "${fld:addr@js}";
document.formEditor.vc_officetel.value = "${fld:officetel@js}";
document.formEditor.vc_zip.value = "${fld:zip@js}";
document.formEditor.vc_mobile.value = "${fld:mobile@js}";
document.formEditor.vc_contact.value = "${fld:contact@js}";
document.formEditor.vc_company.value = "${fld:company@js}";
document.formEditor.vc_jobtype.value = "${fld:jobtype@js}";
document.formEditor.vc_illnessrec.value = "${fld:illnessrec@js}";
document.formEditor.vc_hobby.value = "${fld:hobby@js}";
document.formEditor.vc_pt.value = "${fld:pt@js}";
ccms.util.setCheckboxValue('vc_mc',"${fld:name@js}","formEditor");
document.formEditor.vc_hiddencustomercode.value = "${fld:hiddencustomercode@js}";
document.formEditor.f_moneyleft.value = "${fld:moneyleft}";
document.formEditor.vc_emcontact1.value = "${fld:emcontact1@js}";
document.formEditor.vc_emcontact2.value = "${fld:emcontact2@js}";
document.formEditor.vc_remark.value = "${fld:remark@js}";
