{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"tuid":"${fld:tuid}"
		,"rule_code":"${fld:rule_code@js}"
		,"remark":"${fld:remark@js}"
		,"item_name":"${fld:item_name@js}"
	},
	</rows>
	{}
]}