{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		   "application_id":"${fld:application_id@js}",
		    "tuid":"*/${fld:tuid}/*",
		    "scope_type":"${fld:scope_type}",
		    "campaign_name":"${fld:campaign_name}",
		    "scope_value":"${fld:scope_value}",
		    "start_date":"${fld:start_date}",
		    "end_date":"${fld:end_date}",
		    "created":"${fld:created}",
		    "createdby":"${fld:createdby}"
	},
	</rows>
	{}
]}