{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"application_id":"${fld:application_id@js}",
		"officename":"${fld:officename@js}",
		"i_sex":"${fld:i_sex@js}",
		"vc_name":"${fld:vc_name@js}",
		"vc_mobile":"${fld:vc_mobile}",
		"vc_itime":"${fld:vc_itime}",
		"vc_newmc":"${fld:vc_newmc}",
		"vc_commresult":"${fld:vc_commresult}",
		"entertime":"${fld:entertime}",
		"i_public":"${fld:i_public@js}",
		"num_days":"${fld:num_days}",
		"c_position":"${fld:c_position}",
		"gj_remark":"${fld:gj_remark@js}",
		"vc_code":"${fld:vc_code@js}"
		},
	</rows>
	{}
]}