{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"description":"${fld:description@js}"
		,"domain_text_cn":"${fld:domain_text_cn@js}"
		,"domain_value":"${fld:domain_value}"
	},
	</rows>
	{}
]}