{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"checklink":"${fld:checklink@js}",
		"code":"${fld:code@js}",
		"class_name":"${fld:class_name@js}",
		"class_ename":"${fld:class_ename@js}",
		"times":"${fld:times}",
		"classroomcode":"${fld:classroomcode}",
		"classfee":"${fld:classfee}",
		"status":"${fld:status}",
		"classinfo":"${fld:classinfo@js}",
		"remark":"${fld:remark@js}"
	},
	</rows>
	{}
]}
