{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"cnfg_id":"${fld:cnfg_id}",
		"vc_code":"${fld:_rowNumber}",
		"vc_topic":"${fld:vc_topic}",
		"vc_content":"${fld:vc_content@js}",
		"vc_status":"${fld:vc_status}"
	},
	</rows>
	{}
]}