INSERT INTO cc_ptrest(
	code
	,customercode
	,contractcode
	,ptlevelcode
	,pttotalcount
	,ptleftcount
	,ptnormalmoney
	,ptmoney
	,ptfactfee
	,ptfee
	,scale
	,ptid
	,createdby
	,created
	,pttype
	,ptenddate
	,org_id
) 
values(
	${seq:nextval@seq_cc_ptrest},
	${fld:customercode},
	${fld:contractcode},
	${fld:ptlevelcode},
	${fld:ptcount},
	${fld:ptleftcount},
	(${fld:money}-${fld:ptamount}),
	(${fld:money}-${fld:ptamount}),
	${fld:ptfee},
	${fld:ptfee},
	0,
	${fld:pt},
	'${def:user}',
	{ts '${def:timestamp}'},
	1,
	${fld:ptenddate},
	${def:org}
)
