INSERT INTO cc_contract(
	code
	,contracttype
	,type
	,poptype
	,status
	,salemember
	,salemember1
	,isaudit
	,createdby
	,createdate
	,createtime
	,customercode
	,relatedetail
	,inimoney
	,normalmoney
	,remark
	,org_id
) VALUES(
	${fld:newcontractcode}
	,0
	,1
	,15
	,1
	,${fld:salemember}
	,${fld:salemember1}
	,0
	,'${def:user}'
	,'${def:date}'
	,'${def:time}'
	,${fld:customercode}
	,concat(
		${fld:customercode},';',${fld:cabinetid},';',${fld:months},';',${fld:begindate}::varchar,';'
		,${fld:enddate}::varchar,';',${fld:deposit},';',${fld:inimoney},';',${fld:normalmoney},';'
		,COALESCE(${fld:salemember1},''),';',${fld:salemember},';',${fld:price}
	)
	,${fld:inimoney}
	,${fld:normalmoney}
	,${fld:remark}
	,${def:org}
)