{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		    "gptuid":"${fld:gptuid}",
		    "goods_name":"${fld:goods_name@js}",
		    "storage_name":"${fld:storage_name@js}"
	},
	</rows>
	{}
]}