{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		    "checklink":"${fld:checklink@js}",
		    "custcode":"${fld:custcode@js}",
		    "custname":"${fld:custname@js}",
		    "mobile":"${fld:mobile@js}",
		    "moneycash":"${fld:moneycash}",
		    "moneygift":"${fld:moneygift}"
	},
	</rows>
	{}
]}