{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		    "checklink":"${fld:checklink@js}",
		    "cardcode":"${fld:cardcode@js}",
		    "name":"${fld:name@js}",
		    "mobile":"${fld:mobile@js}",
		    "startdate":"${fld:startdate}",
		    "enddate":"${fld:enddate}",
		    "opentype":"${fld:opentype@js}",
		    "status":"${fld:status@js}",
		    "cardtypename":"${fld:cardtypename@js}",
		    "mcstaff":"${fld:mcstaff@js}",
		    "nowcount":"${fld:nowcount@js}"
	},
	</rows>
	{}
]}