{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"showorder":"${fld:_rowNumber}",
		"name":"${fld:name@js}",
		"guestnum":"${fld:guestnum}",
		"custnum":"${fld:custnum}",
		"visitnum":"${fld:visitnum}",
		"yynum":"${fld:yynum}",
		"msnum":"${fld:msnum}",
		"finishnum":"${fld:finishnum}",
		"totalfee":"${fld:totalfee}",
		"rate":"${fld:rate}",
		"income":"${fld:income}",
		"zhfee":"${fld:zhfee}",
		"averagevisitnum":"",
		"avgfee":"${fld:avgfee}"
	},
	</rows>
	{}
]}
