insert into cc_comm
(
    code,
    cust_type,
    customercode,
    guestcode,
    commtarget,
    commresult,
    nexttime,
    failreason,
    remark,
    preparecode,
    stage,
    callstatus,
    level,
    status,
    createdby,
    created,
    org_id,
    pk_value,
    operatortype
)
values 
(
	${seq:nextval@seq_cc_comm},
    ${fld:cust_type},
    ${fld:customercode},
    ${fld:guestcode},
    ${fld:commtarget},
    ${fld:commresult},
    ${fld:nexttime},
    ${fld:failreason},
    ${fld:remark},
    (case when ${fld:commresult}='2' then ${seq:currval@seq_cc_guest_prepare} else null end),
    ${fld:stage},
    ${fld:callstatus},
    ${fld:level},
    1,
    ${fld:createdby},
    {ts'${def:timestamp}'},
    ${def:org},
    (select code from cc_mcchange where guestcode = ${fld:guestcode} and org_id = ${def:org} order by created desc limit 1),
    0
)
