varchar;varchar;varchar;varchar
field_code;field_name;domain_namespace;field_type
cc_incident.campaign_id;活动编号;campaign;varchar
cc_incident.incident_type;沟通类型;IncidentType;varchar
cc_incident.talk_code;沟通结果;dropSolvedResult;varchar
cc_incident.call_code;拨打状态;OutboundType;varchar
cc_incident.mb_subject;外呼主题;;varchar
cc_incident.agent_update_time;拨打时间;;day
cs_task_pool.is_done;是否完成活动;Optional;varchar