{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"tuid":"${fld:tuid}"
		,"item_name1":"${fld:item_name1@js}"
		,"item_name":"${fld:item_name@js}"
		,"item_code":"${fld:item_code@js}"
		,"show_order":"${fld:show_order}"
		,"show_type":"${fld:show_type@js}"
	},
	</rows>
	{}
]}