{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		    "tuid":"${fld:_rowNumber}",
		    "vc_code":"${fld:code@js}",
		    "i_status":"${fld:i_status@js}",
		    "vc_name":"${fld:name@js}",
		    "i_sex":"${fld:i_sex@js}",
		    "vc_club":"${fld:vc_club@js}",
		    "c_birthdate":"${fld:birthdate}",
		    "vc_rank":"${fld:vc_rank@js}",
		    "vc_email":"${fld:email@js}",
		    "vc_idnumber":"${fld:idnumber}",
		    "vc_nation":"${fld:nation@js}",
		    "vc_hometel":"${fld:hometel@js}",
		    "vc_addr":"${fld:addr@js}",
		    "vc_officetel":"${fld:officetel@js}",
		    "vc_zip":"${fld:zip@js}",
		    "vc_mobile":"${fld:mobile@js}",
		    "vc_contact":"${fld:contact@js}",
		    "vc_company":"${fld:company@js}",
		    "vc_jobtype":"${fld:jobtyp@jse}",
		    "vc_illnessrec":"${fld:illnessrec@js}",
		    "vc_hobby":"${fld:hobby@js}",
		    "vc_pt":"${fld:pt@js}",
		    "vc_mc":"${fld:vc_mc@js}",
		    "vc_hiddencustomercode":"${fld:hiddencustomercode@js}",
		    "f_moneyleft":"${fld:moneyleft}",
		    "vc_emcontact1":"${fld:emcontact1@js}",
		    "vc_emcontact2":"${fld:emcontact2@js}",
		    "vc_iuser":"${fld:createdby}",
		    "c_idate":"${fld:created}",
		    "vc_remark":"${fld:remark@js}"
	},
	</rows>
	{}
]}