{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"tuid":"${fld:tuid}"
		,"item_name":"${fld:item_name@js}"
		,"list_name":"${fld:list_name@js}"
		,"list_code":"${fld:list_code@js}"
		,"list_score":"${fld:list_score}"
		,"show_type":"${fld:show_type@js}"
		,"is_unspeak":"${fld:is_unspeak@js}"
		,"show_order":"${fld:show_order}"
	},
	</rows>
	{}
]}