{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"show_order":"${fld:_rowNumber}",
		"cnfg_id":"${fld:cnfg_id}",
		"deviceid":"${fld:deviceid}",
		"appid":"${fld:appid}",
		"type":"${fld:type@js}",
		"status":"${fld:status}",
		"remark":"${fld:remark}"
	},
	</rows>
	{}
]}
