{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"application_id":"${fld:application_id@js}",
		"show_order":"${fld:_rowNumber}",
		"vc_code":"${fld:vc_code@js}",
		"vc_name":"${fld:vc_name@js}",
		"i_sex":"${fld:i_sex@js}",
		"i_age":"${fld:i_age}",
		"vc_contactway":"${fld:vc_contactway@js}",
		"vc_preparetime":"${fld:vc_preparetime}",
		"vc_iuser":"${fld:vc_iuser@js}",
		"vc_visittime":"${fld:vc_visittime}",
		"vc_visitdate":"${fld:vc_visitdate}",
		"vc_preparedate":"${fld:vc_preparedate}",
		"vc_visitmc":"${fld:vc_visitmc@js}",
		"contractmc":"${fld:contractmc@js}",
		"preparemc":"${fld:preparemc@js}",
		"vc_preparedate":"${fld:vc_preparedate}",
		"dingjin":"${fld:dingjin}",
		"jine":"${fld:jine}",
		"vc_cardtype":"${fld:vc_cardtype@js}",
		"vc_contracode":"${fld:vc_contractcode@js}",
		"prepare_type":"${fld:prepare_type@js}",
		"num_days":"${fld:num_days}",
		"commresult":"${fld:commresult}"
	},
	</rows>
	{}
]}