{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"tuid":"${fld:tuid}"
		,"menu_name":"${fld:menu_name@js}"
		,"pid":"${fld:pid}"
		,"menu_path":"${fld:menu_path@js}"
		,"menu_grade":"${fld:menu_grade}"
		,"icon_path":"${fld:icon_path@js}"
		,"icon_path2":"${fld:icon_path2@js}"
		,"uri":"${fld:uri@js}"
		,"show_order":"${fld:show_order}"
		,"menu_type":"${fld:menu_type@js}"
		,"createdby":"${fld:createdby}"
		,"created":"${fld:created@yyyy-MM-dd HH:mm:ss}"
		,"isshowbtn":"${fld:isshowbtn@js}"
	},
	</rows>
	{}
]}
