{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"application_id":"${fld:application_id@js}",
		"vc_name":"${fld:vc_name@js}",
		"i_sex":"${fld:i_sex@js}",
		"vc_mobile":"${fld:vc_mobile@js}",
		"position":"${fld:position}",
		"gj_commresult":"${fld:gj_commresult}",
		"remark":"${fld:remark}"
			},
	</rows>
	{}
]}