{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"show_order":"${fld:_rowNumber}",
		"name":"${fld:name}",
		"userlogin":"${fld:userlogin}",
		"zongrate":"${fld:zongrate}",
		"msrate":"${fld:msrate}",
		"yyrate":"${fld:yyrate}",
		"guestrate":"${fld:guestrate}"
	},
	</rows>
	{}
]}
