ccms.dialog.notice("添加成功！",1000,function(){
	if($('#guestcode').val()==""){
		if($('#type').val()=="cust"){
			location.href="${def:context}//action/project/fitness/wx/cust/center/tice/crud?customercode="+$('#customercode').val();
		}else{
			location.href="${def:context}/action/project/fitness/wx/mc/mycust/custinfo/crud?customercode="+$('#customercode').val();
		}
	}else{
		location.href="${def:context}/action/project/fitness/wx/mc/myziyuan/gustinfo/crud?guestcode="+$('#guestcode').val();
	}
});