{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"menu_id":"${fld:menu_id}"
		,"position":"${fld:position}"
		,"title":"${fld:title@js}"
		,"parenttitle":"${fld:parenttitle@js}"
	},
	</rows>
	{}
]}