{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		    "vc_code":"${fld:code@js}",
		    "vc_name":"${fld:name@js}",
		    "i_membercount":"${fld:membercount}",
		    "i_type":"${fld:type}",
		    "vc_isoffseason":"${fld:vc_isoffseason@js}",
		    "vc_item":"${fld:item@js}",
		    "i_daycount":"${fld:daycount}",
		    "i_allowcount":"${fld:allowcount}",
		    "f_limitswimtime":"${fld:limitswimtime}",
		    "i_freebathcount":"${fld:freebathcount}",
			"f_scale":"${fld:scale}",
	    	"i_giveday":"${fld:giveday}",
			"i_ptcount":"${fld:ptcount}",
			"i_universal":"${fld:universal}",
			"i_savedaycount":"${fld:savedaycount}",
			"i_status":"${fld:status}",
			"vc_remark":"${fld:remark@js}",
		    "i_count":"${fld:count}",
			"vc_cardtype":"${fld:vc_cardtype@js}",
			"f_cardfee":"${fld:f_cardfee@js}",
			"f_moneyleft":"${fld:moneyleft}"
		},
	</rows>
	{}
]}