{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{ 
		"tuid":"${fld:tuid}"
		,"staff_name":"${fld:staff_name@js}"
		,"msg_title":"${fld:msg_title@js}" 
		,"send_date":"${fld:send_date@yyyy-MM-dd}" 
		,"limit_date":"${fld:limit_date@yyyy-MM-dd}" 
		,"remark":"${fld:remark@js}" 
	},
	</rows>
	{}
]}
