{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"r_show_order":"${fld:_rowNumber}",
		"r_application_id":"${fld:application_id@js}",
		"r_groupname":"${fld:groupname@js}",
		"r_gid":"${fld:gid@js}",
		"r_bid":"${fld:bid@js}",
		"r_price":"${fld:price}",
		"r_startdate":"${fld:startdate}",
		"r_enddate":"${fld:enddate}",
		"r_name":"${fld:name@js}",
		"r_status":"${fld:status}",
		"r_physics_status":"${fld:physics_status@js}",
		"r_mobile":"${fld:mobile@js}"
	},
	</rows>
	{}
]}