{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"radiolink":"${fld:radiolink@js}",
		"vc_code":"${fld:vc_code@js}",
		"show_order":"${fld:_rowNumber}",
		"prepare_time":"${fld:prepare_time}",
		"vc_cardcode":"${fld:vc_cardcode@js}",
		"vc_name":"${fld:vc_name@js}",
		"vc_mobile":"${fld:vc_mobile@js}",
		"i_statusname":"${fld:i_statusname@js}",
		"c_starttime":"${fld:c_starttime}",
		"c_itime":"${fld:c_itime@yyyy-MM-dd HH:mm:ss}",
		"vc_ptlevelname":"${fld:vc_ptlevelname@js}",
		"f_ptfee":"${fld:f_ptfee}",
		"f_scale":"${fld:f_scale}",
		"f_leftcount":"${fld:f_leftcount}",
		"vc_iuser":"${fld:vc_iuser@js}",
		"vc_iusername":"${fld:vc_iusername@js}",
		"pt_name":"${fld:pt_name@js}",
		"ptlevelname":"${fld:ptlevelname@js}"
	},
	</rows>
	{}
]}
