{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		    "checklink":"${fld:checklink@js}",
		    "name":"${fld:name@js}",
		    "sex":"${fld:sex@js}",
		    "mobile":"${fld:mobile@js}",
		    "mc":"${fld:mc@js}",
		    "enddate":"${fld:enddate}"
	},
	</rows>
	{}
]}