INSERT INTO cc_contract(
	code
	,contracttype
	,type
	,poptype
	,status
	,salemember
	,salemember1
	,isaudit
	,createdby
	,createdate
	,createtime
	,customercode
	,relatedetail
	,inimoney
	,normalmoney
	,remark
	,recommendcode
	,relatecode
	,org_id
	,source
	,stage_times
	,stage_times_pay
	,stagemoney
	,campaigncode
) 
SELECT 
	${fld:newcontractcode}
	,3
	,0
	,1
	,1
	,${fld:salemember}
	,${fld:salemember1}
	,0
	,'${def:user}'
	,'${def:date}'
	,'${def:time}'
	,customercode
	,concat(
		customercode,';',get_arr_value(relatedetail,1),';'
		,get_arr_value(relatedetail,2),';'
		,get_arr_value(relatedetail,3),';',COALESCE(${fld:inimoney},0.00),';',COALESCE(get_arr_value(relatedetail,5),''),';',COALESCE(get_arr_value(relatedetail,6),''),';'
		,get_arr_value(relatedetail,7),';',get_arr_value(relatedetail,8),';',get_arr_value(relatedetail,9),';'
		,get_arr_value(relatedetail,10),';',get_arr_value(relatedetail,11),';',get_arr_value(relatedetail,12),';'
		,get_arr_value(relatedetail,13),';;',get_arr_value(relatedetail,15),';',get_arr_value(relatedetail,16),';',COALESCE(${fld:normalmoney},0.00),';'
		,COALESCE(${fld:salemember1},''),';',COALESCE(${fld:salemember},''),';;',get_arr_value(relatedetail,21),';',COALESCE(${fld:current_stage_times_pay},0),';',COALESCE(${fld:stagemoney},0.00)
	)
	,normalmoney
	,${fld:factmoney}
	,${fld:remark}
	,recommendcode
	,code
	,org_id 
	,source 
	,stage_times
	,${fld:current_stage_times_pay}
	,${fld:factmoney}
	,campaigncode 
FROM cc_contract 
WHERE code = ${fld:relatecode} AND org_id = ${def:org} 
