{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{		
		"show_order":"${fld:_rowNumber}",
		"radiolink":"${fld:radiolink@js}",
		"user_id":"${fld:user_id}",
		"userlogin":"${fld:userlogin}",
		"name":"${fld:name@js}",
		"name_en":"${fld:name_en@js}",
		"mobile":"${fld:mobile}",
		"skill_name":"${fld:skill_name@js}",
		"staff_category":"${fld:staff_category@js}",
		"vc_contact":"${fld:vc_contact@js}",
		"i_status":"${fld:i_status@js}",
		"salary":"${fld:salary}",
		"gangwei":"${fld:gangwei}",
		"user_status":"${fld:user_status}",
		"remark":"${fld:remark@js}"
	},
	</rows>
	{}
]}
