{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"show_name":"${fld:show_name@js}"
		,"name":"${fld:name@js}"
		,"total":"${fld:total@js}"
		,"_recordNumber":"${fld:_rowNumber}"
	},
	</rows>
	{}
]}