insert
into
wx_service_pay_notify
values(
nextval('seq_wx_service_pay_notify'),
${app_id},
${device_info},
${sign},
${result_code},
${return_code},
${return_msg},
${trade_type},
${bank_type},
${total_fee},
${transaction_id},
${out_trade_no},
${xml_data},
now()
)