insert
into
wx_service_pay_history
(
tuid,
appid,
bank_type,
cash_fee,
fee_type,
is_subscribe,
mch_id,
nonce_str,
openid,
out_trade_no,
result_code,
return_code,
sign,
time_end,
total_fee,
trade_type,
transaction_id,
created
)
values(
nextval('seq_wx_service_pay_history'),
${fld:appid},
${fld:bank_type},
${fld:cash_fee},
${fld:fee_type},
${fld:is_subscribe},
${fld:mch_id},
${fld:nonce_str},
${fld:openid},
${fld:out_trade_no},
${fld:result_code},
${fld:return_code},
${fld:sign},
${fld:time_end},
${fld:total_fee},
${fld:trade_type},
${fld:transaction_id},
now()
)