{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"user_id":"${fld:user_id}"
		,"userlogin":"${fld:userlogin@js}"
		,"lname":"${fld:lname@js}"
		,"fname":"${fld:fname@js}"
		,"email":"${fld:email@js}"
	},
	</rows>
	{}
]}