{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{ 
		"cust_code":"${fld:cust_code@js}"
		,"cust_name":"${fld:cust_name@js}"
		,"mobile":"${fld:mobile@js}" 
	},
	</rows>
	{}
]}