{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{	
			"show_order":"${fld:_rowNumber}",
			"radiolink":"${fld:radiolink@js}",
			"cardcode":"${fld:cardcode@js}",
		    "cust_name":"${fld:cust_name@js}",
		    "cardtype":"${fld:cardtype@js}",
		    "cardstartdate":"${fld:cardstartdate}",
		    "cardenddate":"${fld:cardenddate}",
		    "adjourndate":"${fld:adjourndate}",
		    "mc":"${fld:mc@js}",
		    "beforedate":"${fld:beforedate@js}",
		    "cardcreated":"${fld:cardcreated@yyyy-MM-dd HH:mm}",
		    "adjourndays":"${fld:adjourndays@js}",
		    "createdate":"${fld:createdate@js}",
		    "createdby":"${fld:createdby@js}",
		    "status":"${fld:status@js}",
		    "remark":"${fld:remark@js}"
	},
	</rows>
	{}
]}
