{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"show_order":"${fld:_rowNumber}",
		"cnfg_id":"${fld:cnfg_id}",
		"appid":"${fld:appid}",
		"remark":"${fld:remark}"
	},
	</rows>
	{}
]}
