{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"post_type":"${fld:post_type@js}"
		,"org_post_name":"${fld:org_post_name@js}"
		,"org_post_id":"${fld:org_post_id}"
		,"hc_name":"${fld:hc_name@js}"
		,"name":"${fld:name@js}"
		,"hc_id":"${fld:hc_id}"
		,"userlogin":"${fld:userlogin@js}"
	},
	</rows>
	{}
]}