INSERT INTO cc_guest(
	code,
	name,
	mobile,
	sex,
	age,
	intention,
	isaddwx,
	communication,
	remark,
	status,
	createdby,
	created,
	initmc,
	mc,
	org_id,
	demand
) VALUES(
	'XG'||to_char({ts'${def:date}'},'yy')||lpad(${seq:nextval@seq_cc_guest}::varchar, 6, '0'),
	${fld:name},
	${fld:mobile},
	${fld:sex},
	${fld:age},
	${fld:intention},
	${fld:isaddwx},
	${fld:communication},
	${fld:remark},
	1,
	'${def:user}',
	{ts '${def:timestamp}'},
	'${def:user}',
	'${def:user}',
	${def:org},
	${fld:demand}
)