{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"show_order":"${fld:_rowNumber}",
		"application_id":"${fld:application_id@js}",
		"groupname":"${fld:groupname@js}",
		"groupcode":"${fld:groupcode@js}",
		"tuid":"${fld:tuid}"
	},
	</rows>
	{}
]}