{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"user_id":"${fld:user_id}"
		,"userlogin":"${fld:userlogin@js}"
		,"mobile":"${fld:mobile@js}"
		,"name":"${fld:name@js}"
		,"email":"${fld:email@js}"
	},
	</rows>
	{}
]}