{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"application_id":"${fld:application_id@js}",
		"show_order":"${fld:_rowNumber}",
		"code":"${fld:code@js}",
		"card_code":"${fld:card_code@js}",
		"name":"${fld:name@js}",
		"mobile":"${fld:mobile@js}",
		"ptname":"${fld:ptname}",
		"pt":"${fld:pt}",
		"pttotalcount":"${fld:pttotalcount}",
		"ptleftcount":"${fld:ptleftcount}",
		"normalmoney":"${fld:normalmoney}",
		"factmoney":"${fld:factmoney}",
		"created":"${fld:created}",
		"ptenddate":"${fld:ptenddate}",
		"salemember":"${fld:salemember@js}",
		"salemember1":"${fld:salemember1@js}",
		"i_status":"${fld:i_status@js}",
		"contracttype":"${fld:contracttype@js}",
		"createdby":"${fld:createdby}"
	},
	</rows>
	{}
]}