{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"gtcode":"${fld:gtcode@js}",
		"thecode":"${fld:thecode@js}",
	    "officename":"${fld:officename@js}",
	    "mobile":"${fld:mobile@js}",
	    "thename":"${fld:thename@js}"
	},
	</rows>
	{}
]}