insert into cc_message
(
   tuid,
   senduser,
   recuser,
   recusername,
   content,
   sendtime,
   org_id
)
values 
(
	${seq:nextval@seq_cc_message},
    '${def:user}',
    ${fld:customercode},
    ${fld:cust_name},
    '会员卡遗失，办理挂失业务',
    {ts'${def:timestamp}'},
    ${def:org}
)
