{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"skill_id":"${fld:skill_id}"
		,"skill_name":"${fld:skill_name@js}"
		,"skill_code":"${fld:skill_code@js}"
		,"remark":"${fld:remark@js}"
	},
	</rows>
	{}
]}