{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"show_order":"${fld:_rowNumber}",
		"checklink":"${fld:checklink@js}",
		"goods_name":"${fld:goods_name@js}",
		"goods_type":"${fld:goods_type@js}",
		"unit":"${fld:unit@js}",
		"standard":"${fld:standard@js}",
		"buyprice":"${fld:buyprice}",
		"fastcode":"${fld:fastcode}"
	},
	</rows>
	{}
]}
