{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"tuid":"${fld:tuid}"
		,"group_name":"${fld:group_name@js}"
		,"remark":"${fld:remark@js}"},
	</rows>
	{}
]}