{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"officename":"${fld:officename@js}",
		"vc_name":"${fld:vc_name@js}",
		"i_sex":"${fld:i_sex@js}",
		"vc_mobile":"${fld:vc_mobile@js}",
		"cc_position":"${fld:cc_position}",
		"gj_commresult":"${fld:gj_commresult}",
		"remark":"${fld:remark}",
		"vc_mc":"${fld:vc_mc@js}"
	},
	</rows>
	{}
]}