insert into ${schema}s_auditlog
(
	auditlog_id,
	operation,
	target_table,
	userlogin,
	extra_info,
	op_date,
	op_time,
	area,
	pkey,
	context_alias,
	recordcount,
	remote_ip
)
values
(
	${seq:nextval@${schema}seq_auditlog},
	'${operation}',
	'${table_code}',
	'${def:user}',
	concat('${operation}','${form_name}'),
	{d '${def:date}'},
	'${def:time}',
	'${form_name}',
	${pk_value},
	'${def:alias}',
	0,
	'${def:remoteaddr}'	
)