INSERT INTO cc_contract(
	code
	,contracttype
	,type
	,poptype
	,status
	,salemember
	,salemember1
	,isaudit
	,createdby
	,createdate
	,createtime
	,customercode
	,relatedetail
	,inimoney
	,normalmoney
	,remark
	,recommendcode
	,relatecode
	,org_id
	,source
	,stage_times
	,campaigncode
) 
SELECT 
	${fld:newcontractcode}
	,3
	,7
	,1
	,1
	,${fld:salemember}
	,${fld:salemember1}
	,0
	,'${def:user}'
	,'${def:date}'
	,'${def:time}'
	,customercode
	,concat(
		customercode,';',get_arr_value(relatedetail,1),';',get_arr_value(relatedetail,2),';',get_arr_value(relatedetail,3),';'
		,COALESCE(normalmoney,0.00),';',get_arr_value(relatedetail,5),';',get_arr_value(relatedetail,6),';'
		,get_arr_value(relatedetail,7),';',get_arr_value(relatedetail,8),';',get_arr_value(relatedetail,9),';'
		,get_arr_value(relatedetail,10),';',get_arr_value(relatedetail,11),';',get_arr_value(relatedetail,12),';'
		,get_arr_value(relatedetail,13),';',get_arr_value(relatedetail,14),';'
		,get_arr_value(relatedetail,15),';',get_arr_value(relatedetail,16),';'
		,COALESCE(normalmoney-COALESCE(factmoney,0.00),0.00),';',COALESCE(${fld:salemember1},''),';',COALESCE(${fld:salemember},''),';'
		,get_arr_value(relatedetail,20),';',get_arr_value(relatedetail,21),';',get_arr_value(relatedetail,22),';'
		,get_arr_value(relatedetail,23),';',get_arr_value(relatedetail,24),';',get_arr_value(relatedetail,25),';'
		,get_arr_value(relatedetail,26)
	)
	,normalmoney
	,normalmoney-COALESCE(factmoney,0.00)
	,${fld:remark}
	,recommendcode
	,code
	,org_id 
	,source 
	,stage_times
	,campaigncode 
FROM cc_contract 
WHERE code = ${fld:relatecode} AND org_id = ${def:org} 
