{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"name":"${fld:name@js}"
		,"sex":"${fld:sex@js}"
		,"mobile":"${fld:mobile@js}"
		,"pt":"${fld:pt@js}"
		,"created":"${fld:created@yyyy-MM-dd}"
		,"tians":"${fld:tians}"
	},
	</rows>
	{}
]}
