{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
			"xuhao":"${fld:_rowNumber}",
		    "vc_code":"${fld:vc_code}",
		    "sv_salesname":"${fld:sv_salesname@js}",
		    "sv_salesname2":"${fld:sv_salesname2@js}",
		    "vc_cardcode":"${fld:vc_cardcode@js}",
		    "vc_customername":"${fld:vc_customername@js}",
		    "vc_typename":"${fld:vc_typename@js}",
		    
		    "vc_detail":"${fld:vc_detail@js}",
		    "f_premoney":"${fld:f_premoney}",
		    "f_money":"${fld:f_money}",
		    "f_cash":"${fld:f_cash}",
		    "f_pos":"${fld:f_pos}",
		    "f_check":"${fld:f_check}",
		    "f_card":"${fld:f_card}",
		    "f_other":"${fld:f_other}",
		    "f_moneyleft":"${fld:f_moneyleft}",
		    "caozuo_zhujian":"${fld:caozuo_zhujian@js}",
		    
		    "vc_ausername":"${fld:vc_ausername@js}",
		    "c_adate":"${fld:c_adate}",
		    "vc_item":"${fld:vc_item@js}",
		    "vc_remark":"${fld:vc_remark@js}",
		    "pay_detail":"${fld:pay_detail@js}",
		    "categories":"${fld:categories@js}"
	},
	</rows>
	{}
]}