{"page":{"total":${fld:total},"pageNo":${fld:pageno},"totalPages":${fld:pages}},"rows":[
	<rows>
	{
		"application_id":"${fld:application_id@js}",
		"show_order":"${fld:_rowNumber}",
		"groupname":"${fld:groupname@js}",
		"cabinetcode":"${fld:cabinetcode@js}",
		"status":"${fld:status}",
		"startdate":"${fld:startdate}",
		"enddate":"${fld:enddate}",
		"customercode":"${fld:customercode@js}",
		"name":"${fld:name@js}",
		"mobile":"${fld:mobile@js}",
		"createdby":"${fld:createdby@js}",
		"remark":"${fld:remark@js}",
		"created":"${fld:created}",
		"isdeposittype":"${fld:isdeposittype}"
	},
	</rows>
	{}
]}